version: '3.8'

services:
  pdf-deidentifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-deidentifier
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1 